name: HighSchoolFootball
favicon: null
layout_spectrum: 0.38266061479225755
typography_spectrum: 0.48591113090515137
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.973458447959274
  lightness: 0.9819778865203261
  saturation: 0.701627564849332
  rhythmicContrast: 0.8733528319280595
purpose: []
