name: HighSchoolFootball
favicon: null
layout_spectrum: 0.49065
typography_spectrum: 0.48591113090515137
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b2b2b2'
    - '#0087be'
    - '#212121'
    - '#dc2a36'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
